# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mUi.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(818, 538)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(520, 350, 281, 111))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox.setFont(font)
        self.groupBox.setObjectName("groupBox")
        self.dillerBtn = QtWidgets.QPushButton(self.groupBox)
        self.dillerBtn.setGeometry(QtCore.QRect(10, 30, 121, 61))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.dillerBtn.setFont(font)
        self.dillerBtn.setObjectName("dillerBtn")
        self.descriptBtn = QtWidgets.QPushButton(self.groupBox)
        self.descriptBtn.setGeometry(QtCore.QRect(150, 30, 121, 61))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.descriptBtn.setFont(font)
        self.descriptBtn.setObjectName("descriptBtn")
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(20, 10, 221, 61))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_2.setFont(font)
        self.groupBox_2.setObjectName("groupBox_2")
        self.nameSearchBtn = QtWidgets.QPushButton(self.groupBox_2)
        self.nameSearchBtn.setGeometry(QtCore.QRect(130, 30, 75, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.nameSearchBtn.setFont(font)
        self.nameSearchBtn.setObjectName("nameSearchBtn")
        self.lineEdit = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdit.setGeometry(QtCore.QRect(10, 30, 113, 21))
        self.lineEdit.setObjectName("lineEdit")
        self.tableWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget.setGeometry(QtCore.QRect(20, 80, 781, 261))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.groupBox_3 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_3.setGeometry(QtCore.QRect(20, 350, 421, 111))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_3.setFont(font)
        self.groupBox_3.setObjectName("groupBox_3")
        self.addDrugBtn = QtWidgets.QPushButton(self.groupBox_3)
        self.addDrugBtn.setGeometry(QtCore.QRect(10, 30, 121, 61))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.addDrugBtn.setFont(font)
        self.addDrugBtn.setObjectName("addDrugBtn")
        self.addDillerBtn = QtWidgets.QPushButton(self.groupBox_3)
        self.addDillerBtn.setGeometry(QtCore.QRect(150, 30, 121, 61))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.addDillerBtn.setFont(font)
        self.addDillerBtn.setObjectName("addDillerBtn")
        self.addDescriptionBtn = QtWidgets.QPushButton(self.groupBox_3)
        self.addDescriptionBtn.setEnabled(True)
        self.addDescriptionBtn.setGeometry(QtCore.QRect(290, 30, 121, 61))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.addDescriptionBtn.setFont(font)
        self.addDescriptionBtn.setObjectName("addDescriptionBtn")
        self.reloadTabBtn = QtWidgets.QPushButton(self.centralwidget)
        self.reloadTabBtn.setGeometry(QtCore.QRect(770, 40, 31, 31))
        self.reloadTabBtn.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icons/update.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.reloadTabBtn.setIcon(icon)
        self.reloadTabBtn.setIconSize(QtCore.QSize(25, 25))
        self.reloadTabBtn.setObjectName("reloadTabBtn")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 818, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Apteka"))
        MainWindow.setToolTip(_translate("MainWindow", "Обновление таблицы"))
        self.groupBox.setTitle(_translate("MainWindow", "Дополнительная информация"))
        self.dillerBtn.setText(_translate("MainWindow", "Поставщики"))
        self.descriptBtn.setText(_translate("MainWindow", "Описание \n"
"препарата"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Поиск по названию"))
        self.nameSearchBtn.setText(_translate("MainWindow", "Поиск"))
        self.groupBox_3.setTitle(_translate("MainWindow", "Редактирование"))
        self.addDrugBtn.setText(_translate("MainWindow", "Добавить \n"
" препарат"))
        self.addDillerBtn.setText(_translate("MainWindow", "Добавить \n"
" поставщика"))
        self.addDescriptionBtn.setText(_translate("MainWindow", "Добавить \n"
" описание"))

