# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dillerAdd.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_DillerAdd(object):
    def setupUi(self, DillerAdd):
        DillerAdd.setObjectName("DillerAdd")
        DillerAdd.resize(460, 490)
        self.centralwidget = QtWidgets.QWidget(DillerAdd)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(30, 30, 141, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(30, 80, 141, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(30, 130, 141, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(30, 180, 141, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(30, 330, 161, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(30, 230, 141, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(30, 280, 151, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.dillerName = QtWidgets.QLineEdit(self.centralwidget)
        self.dillerName.setGeometry(QtCore.QRect(220, 40, 161, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.dillerName.setFont(font)
        self.dillerName.setObjectName("dillerName")
        self.dillerAgent = QtWidgets.QLineEdit(self.centralwidget)
        self.dillerAgent.setGeometry(QtCore.QRect(220, 90, 161, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.dillerAgent.setFont(font)
        self.dillerAgent.setObjectName("dillerAgent")
        self.dillerContry = QtWidgets.QLineEdit(self.centralwidget)
        self.dillerContry.setGeometry(QtCore.QRect(220, 240, 161, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.dillerContry.setFont(font)
        self.dillerContry.setObjectName("dillerContry")
        self.dillerAddres = QtWidgets.QLineEdit(self.centralwidget)
        self.dillerAddres.setGeometry(QtCore.QRect(220, 190, 161, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.dillerAddres.setFont(font)
        self.dillerAddres.setObjectName("dillerAddres")
        self.dillerId = QtWidgets.QLineEdit(self.centralwidget)
        self.dillerId.setGeometry(QtCore.QRect(220, 340, 161, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.dillerId.setFont(font)
        self.dillerId.setObjectName("dillerId")
        self.dillerTel = QtWidgets.QLineEdit(self.centralwidget)
        self.dillerTel.setGeometry(QtCore.QRect(220, 290, 161, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.dillerTel.setFont(font)
        self.dillerTel.setObjectName("dillerTel")
        self.dillerAddBtn = QtWidgets.QPushButton(self.centralwidget)
        self.dillerAddBtn.setGeometry(QtCore.QRect(230, 400, 101, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.dillerAddBtn.setFont(font)
        self.dillerAddBtn.setObjectName("dillerAddBtn")
        self.dillerPos = QtWidgets.QLineEdit(self.centralwidget)
        self.dillerPos.setGeometry(QtCore.QRect(220, 140, 161, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.dillerPos.setFont(font)
        self.dillerPos.setObjectName("dillerPos")
        DillerAdd.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(DillerAdd)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 460, 21))
        self.menubar.setObjectName("menubar")
        DillerAdd.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(DillerAdd)
        self.statusbar.setObjectName("statusbar")
        DillerAdd.setStatusBar(self.statusbar)

        self.retranslateUi(DillerAdd)
        QtCore.QMetaObject.connectSlotsByName(DillerAdd)

    def retranslateUi(self, DillerAdd):
        _translate = QtCore.QCoreApplication.translate
        DillerAdd.setWindowTitle(_translate("DillerAdd", "Добавление поставщика"))
        self.label.setText(_translate("DillerAdd", "Название"))
        self.label_2.setText(_translate("DillerAdd", "Представитель"))
        self.label_3.setText(_translate("DillerAdd", "Должность"))
        self.label_4.setText(_translate("DillerAdd", "Адрес"))
        self.label_5.setText(_translate("DillerAdd", "Идентификатор"))
        self.label_6.setText(_translate("DillerAdd", "Страна"))
        self.label_7.setText(_translate("DillerAdd", "Телефон"))
        self.dillerAddBtn.setText(_translate("DillerAdd", "Добавить"))

