# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'drugAdd.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_DrugAdd(object):
    def setupUi(self, DrugAdd):
        DrugAdd.setObjectName("DrugAdd")
        DrugAdd.resize(460, 490)
        self.centralwidget = QtWidgets.QWidget(DrugAdd)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(30, 30, 141, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(30, 80, 141, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(30, 130, 141, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(30, 180, 141, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(30, 330, 161, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(30, 230, 141, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(30, 280, 151, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.drugId = QtWidgets.QLineEdit(self.centralwidget)
        self.drugId.setGeometry(QtCore.QRect(220, 40, 161, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.drugId.setFont(font)
        self.drugId.setObjectName("drugId")
        self.drugDiller = QtWidgets.QComboBox(self.centralwidget)
        self.drugDiller.setGeometry(QtCore.QRect(220, 140, 161, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.drugDiller.setFont(font)
        self.drugDiller.setObjectName("drugDiller")
        self.drugName = QtWidgets.QLineEdit(self.centralwidget)
        self.drugName.setGeometry(QtCore.QRect(220, 90, 161, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.drugName.setFont(font)
        self.drugName.setObjectName("drugName")
        self.drugCount = QtWidgets.QLineEdit(self.centralwidget)
        self.drugCount.setGeometry(QtCore.QRect(220, 240, 161, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.drugCount.setFont(font)
        self.drugCount.setObjectName("drugCount")
        self.drugUse = QtWidgets.QLineEdit(self.centralwidget)
        self.drugUse.setGeometry(QtCore.QRect(220, 190, 161, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.drugUse.setFont(font)
        self.drugUse.setObjectName("drugUse")
        self.drugSelPrice = QtWidgets.QLineEdit(self.centralwidget)
        self.drugSelPrice.setGeometry(QtCore.QRect(220, 340, 161, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.drugSelPrice.setFont(font)
        self.drugSelPrice.setObjectName("drugSelPrice")
        self.drugPurchPrice = QtWidgets.QLineEdit(self.centralwidget)
        self.drugPurchPrice.setGeometry(QtCore.QRect(220, 290, 161, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.drugPurchPrice.setFont(font)
        self.drugPurchPrice.setObjectName("drugPurchPrice")
        self.drugAddBtn = QtWidgets.QPushButton(self.centralwidget)
        self.drugAddBtn.setGeometry(QtCore.QRect(230, 400, 101, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.drugAddBtn.setFont(font)
        self.drugAddBtn.setObjectName("drugAddBtn")
        DrugAdd.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(DrugAdd)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 460, 21))
        self.menubar.setObjectName("menubar")
        DrugAdd.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(DrugAdd)
        self.statusbar.setObjectName("statusbar")
        DrugAdd.setStatusBar(self.statusbar)

        self.retranslateUi(DrugAdd)
        QtCore.QMetaObject.connectSlotsByName(DrugAdd)

    def retranslateUi(self, DrugAdd):
        _translate = QtCore.QCoreApplication.translate
        DrugAdd.setWindowTitle(_translate("DrugAdd", "Добавление препарата"))
        self.label.setText(_translate("DrugAdd", "Идентификатор"))
        self.label_2.setText(_translate("DrugAdd", "Название"))
        self.label_3.setText(_translate("DrugAdd", "Поставщик"))
        self.label_4.setText(_translate("DrugAdd", "Категория"))
        self.label_5.setText(_translate("DrugAdd", "Цена реализации"))
        self.label_6.setText(_translate("DrugAdd", "Количество"))
        self.label_7.setText(_translate("DrugAdd", "Цена закупочная"))
        self.drugAddBtn.setText(_translate("DrugAdd", "Добавить"))

