# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'drugAddDescription.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_drugAddDescription(object):
    def setupUi(self, drugAddDescription):
        drugAddDescription.setObjectName("drugAddDescription")
        drugAddDescription.resize(693, 453)
        self.centralwidget = QtWidgets.QWidget(drugAddDescription)
        self.centralwidget.setObjectName("centralwidget")
        self.drugGroupTable = QtWidgets.QTableWidget(self.centralwidget)
        self.drugGroupTable.setGeometry(QtCore.QRect(10, 40, 256, 331))
        self.drugGroupTable.setObjectName("drugGroupTable")
        self.drugGroupTable.setColumnCount(0)
        self.drugGroupTable.setRowCount(0)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(30, 0, 221, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(310, 40, 81, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(310, 80, 141, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(310, 120, 81, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.drugGroupSpec = QtWidgets.QTextBrowser(self.centralwidget)
        self.drugGroupSpec.setGeometry(QtCore.QRect(310, 150, 371, 91))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.drugGroupSpec.setFont(font)
        self.drugGroupSpec.setReadOnly(False)
        self.drugGroupSpec.setObjectName("drugGroupSpec")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(310, 260, 81, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.drugGoupSick = QtWidgets.QTextBrowser(self.centralwidget)
        self.drugGoupSick.setGeometry(QtCore.QRect(310, 290, 371, 81))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.drugGoupSick.setFont(font)
        self.drugGoupSick.setReadOnly(False)
        self.drugGoupSick.setObjectName("drugGoupSick")
        self.drugGroup = QtWidgets.QLineEdit(self.centralwidget)
        self.drugGroup.setGeometry(QtCore.QRect(460, 40, 221, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.drugGroup.setFont(font)
        self.drugGroup.setObjectName("drugGroup")
        self.drugUseCode = QtWidgets.QLineEdit(self.centralwidget)
        self.drugUseCode.setGeometry(QtCore.QRect(460, 80, 221, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.drugUseCode.setFont(font)
        self.drugUseCode.setObjectName("drugUseCode")
        self.clearToAddBtn = QtWidgets.QPushButton(self.centralwidget)
        self.clearToAddBtn.setGeometry(QtCore.QRect(10, 380, 31, 31))
        self.clearToAddBtn.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icons/add.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.clearToAddBtn.setIcon(icon)
        self.clearToAddBtn.setIconSize(QtCore.QSize(25, 25))
        self.clearToAddBtn.setObjectName("clearToAddBtn")
        self.deleteBtn = QtWidgets.QPushButton(self.centralwidget)
        self.deleteBtn.setGeometry(QtCore.QRect(50, 380, 31, 31))
        self.deleteBtn.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("icons/delete.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.deleteBtn.setIcon(icon1)
        self.deleteBtn.setIconSize(QtCore.QSize(25, 25))
        self.deleteBtn.setObjectName("deleteBtn")
        self.addDescriptionBtn = QtWidgets.QPushButton(self.centralwidget)
        self.addDescriptionBtn.setGeometry(QtCore.QRect(560, 380, 121, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.addDescriptionBtn.setFont(font)
        self.addDescriptionBtn.setObjectName("addDescriptionBtn")
        self.reloadBtn = QtWidgets.QPushButton(self.centralwidget)
        self.reloadBtn.setGeometry(QtCore.QRect(90, 380, 31, 31))
        self.reloadBtn.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("icons/update.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.reloadBtn.setIcon(icon2)
        self.reloadBtn.setIconSize(QtCore.QSize(25, 25))
        self.reloadBtn.setObjectName("reloadBtn")
        drugAddDescription.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(drugAddDescription)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 693, 21))
        self.menubar.setObjectName("menubar")
        drugAddDescription.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(drugAddDescription)
        self.statusbar.setObjectName("statusbar")
        drugAddDescription.setStatusBar(self.statusbar)

        self.retranslateUi(drugAddDescription)
        QtCore.QMetaObject.connectSlotsByName(drugAddDescription)

    def retranslateUi(self, drugAddDescription):
        _translate = QtCore.QCoreApplication.translate
        drugAddDescription.setWindowTitle(_translate("drugAddDescription", "Добавление/редактирование описания препарата"))
        self.label.setText(_translate("drugAddDescription", "Группа препаратов"))
        self.label_2.setText(_translate("drugAddDescription", "Название"))
        self.label_3.setText(_translate("drugAddDescription", "Идентификатор"))
        self.label_4.setText(_translate("drugAddDescription", "Описание"))
        self.label_5.setText(_translate("drugAddDescription", "Лечение"))
        self.clearToAddBtn.setToolTip(_translate("drugAddDescription", "Очищает поля для добавления нового элемента"))
        self.deleteBtn.setToolTip(_translate("drugAddDescription", "Удаляет выбранный элемент из таблицы"))
        self.addDescriptionBtn.setToolTip(_translate("drugAddDescription", "Добавляет новый элемент в таблицу"))
        self.addDescriptionBtn.setText(_translate("drugAddDescription", "Добавить"))

